apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/guilhermealegre/argocd-applications-study.git
    targetRevision: HEAD
    path: manifests/microservice-a
  destination:
    server: https://kubernetes.default.svc
    namespace: service-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

